export const MainImage = process.env.PUBLIC_URL + '/fresh.jpg'
export const Hair = process.env.PUBLIC_URL + '/hair.png'
export const Skin = process.env.PUBLIC_URL + '/skin.png'
export const Weight = process.env.PUBLIC_URL + '/weight.png'
export const Doctor = process.env.PUBLIC_URL + '/doctor.png'
